src/Entity/Recept.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ReceptRepository")
 */
class Recept
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $naam;

    /**
     * @ORM\Column(type="integer")
     */
    private $prijs_per_liter;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $bereidingswijze;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Bestellingregel", mappedBy="recept")
     */
    private $bestellingregels;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Fruit")
     */
    private $fruit;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Fruit", mappedBy="recept")
     */
    private $fruits;

    public function __construct()
    {
        $this->bestellingregels = new ArrayCollection();
        $this->fruit = new ArrayCollection();
        $this->fruits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNaam(): ?string
    {
        return $this->naam;
    }

    public function setNaam(string $naam): self
    {
        $this->naam = $naam;

        return $this;
    }

    public function getPrijsPerLiter(): ?int
    {
        return $this->prijs_per_liter;
    }

    public function setPrijsPerLiter(int $prijs_per_liter): self
    {
        $this->prijs_per_liter = $prijs_per_liter;

        return $this;
    }

    public function getBereidingswijze(): ?string
    {
        return $this->bereidingswijze;
    }

    public function setBereidingswijze(string $bereidingswijze): self
    {
        $this->bereidingswijze = $bereidingswijze;

        return $this;
    }

    /**
     * @return Collection|Bestellingregel[]
     */
    public function getBestellingregels(): Collection
    {
        return $this->bestellingregels;
    }

    public function addBestellingregel(Bestellingregel $bestellingregel): self
    {
        if (!$this->bestellingregels->contains($bestellingregel)) {
            $this->bestellingregels[] = $bestellingregel;
            $bestellingregel->setRecept($this);
        }

        return $this;
    }

    public function removeBestellingregel(Bestellingregel $bestellingregel): self
    {
        if ($this->bestellingregels->contains($bestellingregel)) {
            $this->bestellingregels->removeElement($bestellingregel);
            // set the owning side to null (unless already changed)
            if ($bestellingregel->getRecept() === $this) {
                $bestellingregel->setRecept(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Fruit[]
     */
    public function getFruit(): Collection
    {
        return $this->fruit;
    }

    public function addFruit(Fruit $fruit): self
    {
        if (!$this->fruit->contains($fruit)) {
            $this->fruit[] = $fruit;
        }

        return $this;
    }

    public function removeFruit(Fruit $fruit): self
    {
        if ($this->fruit->contains($fruit)) {
            $this->fruit->removeElement($fruit);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->naam;
    }

    /**
     * @return Collection|Fruit[]
     */
    public function getFruits(): Collection
    {
        return $this->fruits;
    }


}

src/Form/ReceptType.php
<?php

namespace App\Form;

use App\Entity\Recept;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReceptType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('naam')
            ->add('prijs_per_liter')
            ->add('bereidingswijze')
            ->add('fruit')

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Recept::class,
        ]);
    }
}

src/Controller/ReceptController.php
<?php

namespace App\Controller;

use App\Entity\Recept;
use App\Form\ReceptType;
use App\Repository\ReceptRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/recept")
 */
class ReceptController extends AbstractController
{
    /**
     * @Route("/recepten", name="recept_index", methods={"GET"})
     */
    public function index(ReceptRepository $receptRepository): Response
    {
        return $this->render('recept/index.html.twig', [
            'recepts' => $receptRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="recept_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $recept = new Recept();
        $form = $this->createForm(ReceptType::class, $recept);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($recept);
            $entityManager->flush();

            return $this->redirectToRoute('recept_index');
        }

        return $this->render('recept/new.html.twig', [
            'recept' => $recept,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="recept_show", methods={"GET"})
     */
    public function show(Recept $recept): Response
    {
        return $this->render('recept/show.html.twig', [
            'recept' => $recept,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="recept_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Recept $recept): Response
    {
        $form = $this->createForm(ReceptType::class, $recept);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('recept_index');
        }

        return $this->render('recept/edit.html.twig', [
            'recept' => $recept,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="recept_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Recept $recept): Response
    {
        if ($this->isCsrfTokenValid('delete'.$recept->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($recept);
            $entityManager->flush();
        }

        return $this->redirectToRoute('recept_index');
    }
}

templates/recept/_delete_form.html.twig
<form method="post" action="{{ path('recept_delete', {'id': recept.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ recept.id) }}">
    <button class="btn">Delete</button>
</form>

templates/recept/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-lg btn-primary">{{ button_label|default('opslaan') }}</button>
{{ form_end(form) }}

templates/recept/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Recept{% endblock %}

{% block body %}
    <h1>Edit Recept</h1>

    {{ include('recept/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('recept_index') }}">back to list</a>

    {{ include('recept/_delete_form.html.twig') }}
{% endblock %}

templates/recept/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recept index{% endblock %}

{% block body %}
<div class="container-md">
    <h1>RECEPTEN</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Naam</th>
                <th>Bereidingswijze</th>

            </tr>
        </thead>
        <tbody>
        {% for recept in recepts %}
            <tr>
                <td>{{ recept.naam }}</td>
                <td>{{ recept.bereidingswijze }}</td>


            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('recept_new') }}">Create new</a>
</div>
{% endblock %}

templates/recept/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Recept{% endblock %}

{% block body %}
<div class="container-md">
    <h1>Recept</h1>

    {{ include('recept/_form.html.twig') }}

 </div>
{% endblock %}

templates/recept/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recept{% endblock %}

{% block body %}
    <h1>Recept</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ recept.id }}</td>
            </tr>
            <tr>
                <th>Naam</th>
                <td>{{ recept.naam }}</td>
            </tr>
            <tr>
                <th>Prijs_per_liter</th>
                <td>{{ recept.prijsPerLiter }}</td>
            </tr>
            <tr>
                <th>Bereidingswijze</th>
                <td>{{ recept.bereidingswijze }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('recept_index') }}">back to list</a>

    <a href="{{ path('recept_edit', {'id': recept.id}) }}">edit</a>

    {{ include('recept/_delete_form.html.twig') }}
{% endblock %}